package com.greenbit.gbmsapi;

public class GBMSAPIJavaWrapperDefinesHwAntifakeFingerDetectionDiagnostic {
    public static int GBMSAPI_HW_ANTIFAKE_DIAGNOSTIC_FINGER_AREA_SMALL = 0x00000001;
    public static int GBMSAPI_HW_ANTIFAKE_DIAGNOSTIC_FINGER_DISPLACED_UP = 0x00000002;
    public static int GBMSAPI_HW_ANTIFAKE_DIAGNOSTIC_FINGER_DISPLACED_DOWN = 0x00000004;
    public static int GBMSAPI_HW_ANTIFAKE_DIAGNOSTIC_FINGER_DISPLACED_LEFT = 0x00000008;
    public static int GBMSAPI_HW_ANTIFAKE_DIAGNOSTIC_FINGER_DISPLACED_RIGHT = 0x00000010;
    public static int GBMSAPI_HW_ANTIFAKE_DIAGNOSTIC_FINGER_SHIFT_DETECTED = 0x00000020;
    public static int GBMSAPI_HW_ANTIFAKE_DIAGNOSTIC_FINGER_REMOVED_TOO_EARLY = 0x00000040;
    public static int GBMSAPI_HW_ANTIFAKE_DIAGNOSTIC_PRESS_FINGER_HARDER = 0x00000080;
}
