
// declare all constants related to boiler app
export const LOGIN_UPDATE = 'LOGIN_UPDATE';

export const TOGGLESHOWIMAGEMODAL = 'TOGGLESHOWIMAGEMODAL';
export const TOGGLEIMAGEVIEWMODAL = 'TOGGLEIMAGEVIEWMODAL';
export const TOGGLESUCCESSMODAL = 'TOGGLESUCCESSMODAL';
export const TOGGLEERRORMODAL = 'TOGGLEERRORMODAL';

export const CAPTURE_UPDATE = 'CAPTURE_UPDATE';

//profile
export const PROFILE_UPDATE = 'PROFILE_UPDATE';
export const GET_USER = 'GET_USER';
export const LOGIN_USER = 'LOGIN_USER';

//loader
export const LOGIN_LOADING = 'LOGIN_LOADING';
export const INSURANCE_LOADING = 'INSURANCE_LOADING';
export const ID_LOADING = 'ID_LOADING';
export const PASSPORT_LOADING = 'PASSPORT_LOADING';
export const ATTENDANCE_LOADING = 'ATTENDANCE_LOADING';
export const PROFILE_LOADING = 'PROFILE_LOADING';

//errors
export const GET_ERROR_MESSAGE = 'GET_ERROR_MESSAGE';
export const GET_ERRORS = 'GET_ERRORS';