# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

# use_frameworks!

target 'Boiler' do
  # Pods for Boiler

  platform :ios, '9.0'
  # pod 'react-native-fbsdk', :path => '../node_modules/react-native-fbsdk'
  pod 'FBSDKCoreKit'
  pod 'FBSDKLoginKit'
  pod 'FBSDKShareKit'
  pod 'AccountKit'
  pod 'TwitterKit', '~> 3.3.0'
  pod 'GoogleAnalytics'

  pod 'AppCenter/Crashes', '~> 1.13.2'
  pod 'AppCenter/Analytics', '~> 1.13.2'
  pod 'AppCenterReactNativeShared', '~> 1.12.2'
  pod 'Firebase/Analytics'
  pod 'Firebase/Messaging'
  pod 'RNGoogleSignin', :path => '../node_modules/react-native-google-signin'

  pod 'RNAccountKit', :path => '../node_modules/react-native-facebook-account-kit/ios'

  pod 'RNImageCropPicker', :path => '../node_modules/react-native-image-crop-picker'

  pod 'BVLinearGradient', :path => '../node_modules/react-native-linear-gradient'

  pod 'react-native-spinkit', :path => '../node_modules/react-native-spinkit'

  pod 'react-native-webview', :path => '../node_modules/react-native-webview'

  pod 'rn-fetch-blob', :path => '../node_modules/rn-fetch-blob'

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  # CodePush plugin dependency
  pod 'CodePush', :path => '../node_modules/react-native-code-push'

  react_native_path = "../node_modules/react-native"

  pod 'React', :path => "#{react_native_path}", :subspecs => [
    'Core',
    'CxxBridge',
    'DevSupport',
    'RCTText',
    'RCTNetwork',
    'RCTImage',
    'RCTWebSocket',
  ]

  pod "yoga", :path => "#{react_native_path}/ReactCommon/yoga"
  pod 'Folly', :podspec => "#{react_native_path}/third-party-podspecs/Folly.podspec"

  pod 'RNCPushNotificationIOS', :path => '../node_modules/@react-native-community/push-notification-ios'

  pod 'react-native-contacts', :path => '../node_modules/react-native-contacts'

  pod 'react-native-sms', :path => '../node_modules/react-native-sms'

  pod 'react-native-sqlite-storage', :path => '../node_modules/react-native-sqlite-storage'

  pod 'react-native-camera', :path => '../node_modules/react-native-camera'

  pod 'RNFS', :path => '../node_modules/react-native-fs'

  target 'BoilerTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.name == "React"
      target.remove_from_project
    end
  end
end
