const BACKGROUND = '#FAFAFA';
const BLUE = '#2042B8';
const ORANGE = '#FF6600';
const WHITE = '#FFFFFF';
const LIGHTBACKGROUND = '#F9F9F9';
const DISABLED = '#929BBB';
const GRAY = '#707070';
const SHADOWBLUE = '#B5C4F9';
const LIGHTBLUE = '#7292FF';
const FOODRED = '#CE2601'
const RED = '#FF0000';
const GREEN = '#03961F'
const BLACK = '#1D1C1C';
const SHADOWBLUEBORDER = '#7ADBF3'

export {
    BLUE, ORANGE, WHITE, BACKGROUND, GRAY, LIGHTBACKGROUND, SHADOWBLUE,
    FOODRED, RED, GREEN, BLACK, LIGHTBLUE, SHADOWBLUEBORDER,
    DISABLED
}
