const FONTFAMILYREGULAR = "Nunito Regular"
const FONTFAMILYTHIN = "WorkSans-Thin"
const FONTFAMILYEXTRALIGHT = "WorkSans-ExtraLight"
const FONTFAMILYLIGHT = "WorkSans-Light"
const FONTFAMILYMEDIUM = "WorkSans-Medium"
const FONTFAMILYSEMIBOLD = "WorkSans-SemiBold"
const FONTFAMILYEXTRABOLD = "WorkSans-ExtraBold"
const FONTFAMILYBOLD = "Nunito Bold"
const FONTFAMILYBLACK = "WorkSans-Black"

export {
    FONTFAMILYBLACK, FONTFAMILYBOLD,
    FONTFAMILYLIGHT, FONTFAMILYMEDIUM,
    FONTFAMILYREGULAR, FONTFAMILYTHIN,
    FONTFAMILYSEMIBOLD, FONTFAMILYEXTRALIGHT,
    FONTFAMILYEXTRABOLD

}